- id: fastapi-codegen
  name: fastapi-codegen
  description: "Fastapicodegen"
  entry: fastapi-codegen
  language: python
  minimum_pre_commit_version: 2.9.2
  require_serial: true
  always_run: true
  types_or: []
  exclude: '.*'
